#!/bin/sh -e
# hornetq startup script
#chkconfig: 2345 80 05
#description: hornetq
 
# Define some variables
# Name of app ( hornetq, Confluence, etc )
APP=hornetq
# Name of the user to run as
USER=hornetq
# Location of application's bin directory
BASE=/usr/local/hornetq/current
# Location of Java JDK
#export JAVA_HOME=/usr/lib/jvm/java-6-sun
 
case "$1" in
  # Start command
  start)
    echo "Starting $APP"
   /bin/su -m $USER -c "cd $BASE/logs && $BASE/bin/run.sh &> /dev/null" &
    ;;
  # Stop command
  stop)
    echo "Stopping $APP"
    /bin/su -m $USER -c "$BASE/bin/stop.sh &> /dev/null"
    echo "$APP stopped successfully"
    ;;
   # Restart command
   restart)
        $0 stop
        sleep 5
        $0 start
        ;;
  *)
    echo "Usage: /etc/init.d/$APP {start|restart|stop}"
    exit 1
    ;;
esac
 
exit 0

