#!/bin/sh -e
# Tomcat6-1 startup script
#chkconfig: 2345 80 05
#description: Tomcat6-1
 
# Define some variables
# Name of app ( Tomcat6-1, Confluence, etc )
APP=Tomcat6-1
# Name of the user to run as
USER=bime
# Location of application's bin directory
BASE=/usr/local/tomcat6-1
# Location of Java JDK
#export JAVA_HOME=/usr/lib/jvm/java-6-sun
 
case "$1" in
  # Start command
  start)
    echo "Starting $APP"
    /bin/su -m $USER -c "cd $BASE/logs && $BASE/bin/startup.sh &> /dev/null"
    ;;
  # Stop command
  stop)
    echo "Stopping $APP"
    /bin/su -m $USER -c "$BASE/bin/shutdown.sh &> /dev/null"
    echo "$APP stopped successfully"
    ;;
   # Restart command
   restart)
        $0 stop
        sleep 5
        $0 start
        ;;
  *)
    echo "Usage: /etc/init.d/$APP {start|restart|stop}"
    exit 1
    ;;
esac
 
exit 0

